# Generated by Django 5.2.15 on 2026-06-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('run_id', models.CharField(blank=True, max_length=64)),
                ('seq', models.BigIntegerField(default=0)),
                ('source', models.CharField(max_length=16)),
                ('kind', models.CharField(max_length=16)),
                ('summary', models.TextField()),
                ('detail', models.TextField(blank=True)),
                ('expand', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['session_id', 'id'], name='agent_agent_session_3e99d8_idx')],
            },
        ),
    ]
