# Generated by Django 5.2.15 on 2026-06-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_agentevent_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='verdict',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
