# Generated by Django 5.2.15 on 2026-06-20 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_agentrun_verdict'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=64)),
                ('case_id', models.CharField(db_index=True, max_length=256)),
                ('agent_name', models.CharField(blank=True, max_length=64)),
                ('original_verdict', models.JSONField(blank=True, default=None, null=True)),
                ('analyst_verdict', models.JSONField(blank=True, default=None, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatternEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('verdict', models.CharField(choices=[('tp', 'True positive'), ('fp', 'False positive')], default='fp', max_length=8)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('required_evidence', models.JSONField(blank=True, default=list)),
                ('invalidators', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('owner', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BaselineSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('endpoint', 'Endpoint'), ('user', 'User'), ('service', 'Service')], max_length=16)),
                ('subject_id', models.CharField(max_length=256)),
                ('feature', models.CharField(max_length=64)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('window_days', models.PositiveIntegerField(default=30)),
                ('health', models.CharField(choices=[('fresh', 'Fresh'), ('stale', 'Stale'), ('missing', 'Missing'), ('low_data', 'Low data')], default='fresh', max_length=16)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['subject_type', 'subject_id', 'feature'],
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='agent_basel_subject_08edba_idx')],
                'unique_together': {('subject_type', 'subject_id', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='PatternCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('verdict', models.CharField(choices=[('tp', 'True positive'), ('fp', 'False positive')], default='fp', max_length=8)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('required_evidence', models.JSONField(blank=True, default=list)),
                ('invalidators', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('reviewer', models.CharField(blank=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='agent.feedbackentry')),
                ('promoted_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_candidates', to='agent.patternentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
