# Generated by Django 5.2.15 on 2026-06-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_feedbackentry_patternentry_baselinesnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=64, unique=True)),
                ('max_steps', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('max_tool_calls', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('tool_policy', models.JSONField(blank=True, default=None, null=True)),
                ('stream_intent', models.BooleanField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['agent_name'],
            },
        ),
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=32, unique=True)),
                ('action', models.CharField(choices=[('auto_close', 'Auto-close'), ('auto_escalate', 'Auto-escalate'), ('hold', 'Hold for analyst'), ('none', 'No action')], default='hold', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['verdict'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('dedupe_window', models.PositiveIntegerField(default=600)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_type'],
            },
        ),
    ]
