# Generated by Codex on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0009_agentconfig_escalationrule_workflowconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowTriggerConfig",
            fields=[
                ("id", models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("webhook", "Webhook"),
                            ("schedule", "Schedule"),
                            ("poller", "Poller"),
                        ],
                        default="webhook",
                        max_length=16,
                    ),
                ),
                ("provider_key", models.CharField(max_length=64)),
                ("event_type", models.CharField(max_length=64)),
                ("enabled", models.BooleanField(default=True)),
                ("dedupe_window", models.PositiveIntegerField(default=600)),
                ("secret", models.CharField(blank=True, max_length=256)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["provider_key", "event_type", "name"],
            },
        ),
    ]
