# Generated by Django 5.2.15 on 2026-06-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_workflowtriggerconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackentry',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='feedbackentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedbackentry',
            name='run_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
