# Generated by Django 5.2.15 on 2026-06-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_feedback_mutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackentry',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
