# Generated by Django 5.2.15 on 2026-06-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_feedback_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineSubjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('endpoint', 'Endpoint'), ('user', 'User'), ('service', 'Service')], max_length=16)),
                ('subject_id', models.CharField(max_length=256)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['subject_type', 'subject_id'],
                'unique_together': {('subject_type', 'subject_id')},
            },
        ),
    ]
