# Generated by Django 5.2.15 on 2026-06-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0013_baselinesubjectconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineComputeConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('window_days', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
